#!/bin/bash

# Setup script for local development
# This script creates the .env.local file with the correct PocketBase URL

set -e

echo "=========================================="
echo "🔧 Running Setup Script"
echo "=========================================="

echo ""
echo "💻 Setting up local development environment"
POCKETBASE_URL="http://localhost:8090"

# Always recreate .env.local file
echo ""
echo "📝 Creating .env.local..."

cat > .env.local << EOF
# Auto-generated by .devcontainer/setup.sh
# Generated at: $(date)
# PocketBase Configuration

# Client-side URL (browser requests)
VITE_PUBLIC_POCKETBASE_URL=${POCKETBASE_URL}

# Server-side URL (for API routes running in container)
VITE_POCKETBASE_URL=http://pocketbase:8090
EOF

echo ""
echo "✅ Created .env.local:"
echo "=========================================="
cat .env.local
echo "=========================================="
echo ""
echo "🎉 PocketBase Admin UI will be available at: ${POCKETBASE_URL}/_/"
echo ""
