#!/bin/bash

# Setup script for GitHub Codespaces
# This script creates the .env.local file with the correct URLs

ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

# Check if we're in GitHub Codespaces
if [ -n "$CODESPACE_NAME" ] && [ -n "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN" ]; then
    echo "🚀 Detected GitHub Codespaces environment"
    
    # Construct the Codespaces forwarded URL for port 8000
    SUPABASE_URL="https://${CODESPACE_NAME}-8000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}"
    
    echo "📝 Setting NEXT_PUBLIC_SUPABASE_URL to: $SUPABASE_URL"
else
    echo "💻 Local development environment detected"
    SUPABASE_URL="http://localhost:8000"
fi

# Create .env.local file
cat > .env.local << EOF
# Auto-generated by .devcontainer/setup.sh
# Supabase Configuration

# Client-side URL (browser requests)
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}

# Supabase Anonymous Key
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}

# Server-side URL (for API routes running in container)
SUPABASE_URL=http://supabase-kong:8000
EOF

echo "✅ Created .env.local with correct Supabase URLs"
cat .env.local

